# -*- coding: utf-8 -*-
"""emailspamdetection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dob7axSMO6Jq93vdnqx6gmC2JDVbdj4K
"""

!pip install kagglehub -q

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import re
import string
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')

# Dataset 1: SMS Spam Collection
sms_url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

sms_df = pd.read_table(
    sms_url,
    header=None,
    names=['label', 'message']
)

print("SMS Dataset Loaded")
print(sms_df.head())

# Dataset 2: Spam Email Dataset (using kagglehub)
import kagglehub

dataset_path = kagglehub.dataset_download('uciml/sms-spam-collection-dataset', 'spam.csv')

email_df = pd.read_csv(
    dataset_path,
    encoding='latin-1'
)

email_df = email_df.rename(columns={'v1': 'label', 'v2': 'message'})
email_df = email_df.loc[:, ~email_df.columns.str.contains('^Unnamed')]

print("Email Dataset Loaded")
print(email_df.head())

# Dataset 3: Additional Spam Dataset

dataset3_url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/sms.tsv"

dataset3 = pd.read_table(
    dataset3_url,
    header=None,
    names=['label', 'message']
)

print("Dataset 3 Loaded")
print(dataset3.head())

df = pd.concat(
    [sms_df, email_df, dataset3],
    ignore_index=True
)

# Remove duplicates
df.drop_duplicates(inplace=True)

print("Combined Dataset Shape:")
print(df.shape)

print(df.head())

print(df.shape)

print(df['label'].value_counts())

stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    words = text.split()
    words = [stemmer.stem(word) for word in words if word not in stop_words]

    return " ".join(words)

df['clean_message'] = df['message'].apply(clean_text)

print(df[['message', 'clean_message']].head())

df['label'] = df['label'].map({'ham':0, 'spam':1})

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df['clean_message']).toarray()

y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

models = {
    "Gaussian Naive Bayes": GaussianNB(),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC(kernel='linear')
}

accuracy_results = {}

for name, model in models.items():

    print("="*50)
    print(f"Model: {name}")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracy_results[name] = accuracy

    print("Accuracy:", accuracy)
    print("\nClassification Report")
    print(classification_report(y_test, y_pred))
    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f'Confusion Matrix - {name}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import pandas as pd
import kagglehub

nltk.download('stopwords')

stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[\W_]+', ' ', text) # Keep only alphanumeric and underscore
    words = text.split()
    words = [stemmer.stem(word) for word in words if word not in stop_words]
    return " ".join(words)

sms_url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
sms_df = pd.read_table(sms_url, header=None, names=['label', 'message'])

dataset_path = kagglehub.dataset_download('uciml/sms-spam-collection-dataset', 'spam.csv')
email_df = pd.read_csv(dataset_path, encoding='latin-1')
email_df = email_df.rename(columns={'v1': 'label', 'v2': 'message'})
email_df = email_df.loc[:, ~email_df.columns.str.contains('^Unnamed')]

dataset3_url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/sms.tsv"
dataset3 = pd.read_table(dataset3_url, header=None, names=['label', 'message'])

df = pd.concat([sms_df, email_df, dataset3], ignore_index=True)
df.drop_duplicates(inplace=True)

df['clean_message'] = df['message'].apply(clean_text)

df['label'] = df['label'].map({'ham':0, 'spam':1})

tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df['clean_message']).toarray()
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



best_model = SVC(kernel='linear')
best_model.fit(X_train, y_train)


test_emails = [
    "Congratulations! You won ₹50,000. Click here to get money!", # Spam example
    "URGENT! Your account has been compromised. Click here to secure it now!", # Spam example
    "Hey, how are you doing? Let's catch up soon.", # Ham example
    "Meeting at 3 PM today. Please bring your report.", # Ham example
    "Free concert tickets for you! Claim your prize now!", # Spam example
    "Can you pick up groceries on your way home?"
]

print("\n--- Predicting for new emails ---")
for i, email in enumerate(test_emails):
    cleaned_test_email = clean_text(email)
    vectorized_test_email = tfidf.transform([cleaned_test_email]).toarray()
    prediction = best_model.predict(vectorized_test_email)

    result = "Spam Email" if prediction[0] == 1 else "Ham Email"
    print(f"\nOriginal Email {i+1}: {email}")
    print(f"Prediction: {result}")